#spring.application.name=gateway-service
#
#
#server.port=9098
#eureka.client.serviceUrl.defaultZone=http://localhost:9091/eureka/
#
#management.endpoints.web.exposure.include=*
#management.endpoint.gateway.enabled=true
#
#spring.cloud.gateway.discovery.locator.enabled=true
#
#
## configure info endpoint for application details using localhost:9090/actuator/info
#management.info.env.enabled=true
#info.app.name=gateway-service
#info.app.description=API Gateway for the microservices application
#info.app.version=1.0.0



